// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Ambient_Music___Ambient_1 = "Ambient Music - Ambient 1",
  Arrow_Blue = "Arrow Blue",
  BaseSnow_glb = "BaseSnow.glb",
  Broom_glb = "Broom.glb",
  Buttons = "Buttons",
  CWGSign01_glb = "CWGSign01.glb",
  CWGSign01_glb_2 = "CWGSign01.glb_2",
  DCLRGL_Banner_glb = "DCLRGL_Banner.glb",
  Home01_glb = "Home01.glb",
  Invisible_Sphere = "Invisible Sphere",
  Invisible_Sphere_10 = "Invisible Sphere_10",
  Invisible_Sphere_11 = "Invisible Sphere_11",
  Invisible_Sphere_12 = "Invisible Sphere_12",
  Invisible_Sphere_13 = "Invisible Sphere_13",
  Invisible_Sphere_2 = "Invisible Sphere_2",
  Invisible_Sphere_3 = "Invisible Sphere_3",
  Invisible_Sphere_4 = "Invisible Sphere_4",
  Invisible_Sphere_5 = "Invisible Sphere_5",
  Invisible_Sphere_6 = "Invisible Sphere_6",
  Invisible_Sphere_7 = "Invisible Sphere_7",
  Invisible_Sphere_8 = "Invisible Sphere_8",
  Invisible_Sphere_9 = "Invisible Sphere_9",
  LeaderBoardPanel01_glb = "LeaderBoardPanel01.glb",
  Penguin_glb = "Penguin.glb",
  PenguinCrowd_glb = "PenguinCrowd.glb",
  PenguinCrowd_glb_10 = "PenguinCrowd.glb_10",
  PenguinCrowd_glb_11 = "PenguinCrowd.glb_11",
  PenguinCrowd_glb_12 = "PenguinCrowd.glb_12",
  PenguinCrowd_glb_13 = "PenguinCrowd.glb_13",
  PenguinCrowd_glb_2 = "PenguinCrowd.glb_2",
  PenguinCrowd_glb_3 = "PenguinCrowd.glb_3",
  PenguinCrowd_glb_4 = "PenguinCrowd.glb_4",
  PenguinCrowd_glb_5 = "PenguinCrowd.glb_5",
  PenguinCrowd_glb_6 = "PenguinCrowd.glb_6",
  PenguinCrowd_glb_7 = "PenguinCrowd.glb_7",
  PenguinCrowd_glb_9 = "PenguinCrowd.glb_9",
  PenguinFriend_glb = "PenguinFriend.glb",
  PenguinPlayer_glb = "PenguinPlayer.glb",
  Playground_glb = "Playground.glb",
  RedLine_glb = "RedLine.glb",
  RedLine_glb_2 = "RedLine.glb_2",
  TriggerLose = "TriggerLose",
  snowbarrier_glb = "snowbarrier.glb",
} 
